apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-git-clone-ca
spec:
  params:
    - default: ''
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: master
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - default: user-ca-bundle
      description: configmap with the ca
      name: cm-ca-name
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: sslVerify
          value: 'true'
        - name: cm-ca-name
          value: $(params.cm-ca-name)
      taskRef:
        kind: ClusterTask
        name: git-clone-custom
      workspaces:
        - name: output
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
